### ISSUE TITLE
domain-search doesn't use RFC1035 compressed labels

### ISSUE THREAD

**Issue by dmgeurts** [opennetadmin/build_isc_dhcp#15]
https://kb.isc.org/docs/isc-dhcp-44-manual-pages-dhcp-options#STANDARD%20DHCPV4%20OPTIONS

Whether I separate search domain entries with space, semi-colon or comma. They're always recorded as a single label. Meaning the client interprets them as a single domain.

It would be good to either inform the user of the format required in the GUI. Or to interpret either comma, space, (semi-)colon etc. as delimiters and record domains in the ISC config as "domain.a", "domain.2", "domain.3", instead of "domain.1, domain.2, domain.3".

Or tell me where I'm wrong as I've not been able to make it work.

**Comment by mattpascoe** [comment]
I believe this has been addressed in the latest version of the build_isc_dhcp plugin (v1.6).  You can look at the pull request #14 for the detail, but it should support space or comma separated lists in the search-domain option.
